#!/usr/bin/env tsx
/**
 * Emits `src/types/keys.generated.ts` from the artifacts in `schema/`.
 *
 * The key-name tables and the modifier enum are the only parts of the Karabiner
 * AST that are pure data, and they are the only parts that go stale when
 * Karabiner ships a release. Everything structural stays hand-written in
 * `src/types/snaplink.ts`, where the gotcha citations live.
 *
 *   npm run codegen         rewrite
 *   npm run codegen:check   exit 1 if stale
 *
 * Refresh the inputs first when Karabiner adds names:
 *   make -C schema keycodes KE_SRC=/path/to/Karabiner-Elements
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
const KEYCODES = join(REPO, "schema", "karabiner-keycodes.json");
const SCHEMA = join(REPO, "schema", "karabiner-rule.schema.json");
const OUT = join(REPO, "src", "types", "keys.generated.ts");

/** `[table name in karabiner-keycodes.json, exported TypeScript alias]`. */
const TABLES: readonly (readonly [string, string])[] = [
  ["key_code", "KeyCode"],
  ["consumer_key_code", "ConsumerKeyCode"],
  ["apple_vendor_keyboard_key_code", "AppleVendorKeyboardKeyCode"],
  ["apple_vendor_top_case_key_code", "AppleVendorTopCaseKeyCode"],
  ["generic_desktop", "GenericDesktopKeyCode"],
  ["pointing_button", "PointingButton"],
];

function readJson(path: string): unknown {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as unknown;
  } catch (cause) {
    throw new Error(`cannot read ${relative(REPO, path)}`, { cause });
  }
}

/** Resolve a dotted path, failing loudly rather than emitting an empty union. */
function at(root: unknown, path: readonly (string | number)[], label: string): unknown {
  let node: unknown = root;
  for (const step of path) {
    if (node === null || typeof node !== "object") {
      throw new Error(`${label}: ${path.join(".")} — not an object at "${String(step)}"`);
    }
    node = (node as Record<string | number, unknown>)[step];
  }
  if (node === undefined) throw new Error(`${label}: ${path.join(".")} is missing`);
  return node;
}

function strings(value: unknown, label: string): string[] {
  if (!Array.isArray(value) || value.length === 0 || value.some((v) => typeof v !== "string")) {
    throw new Error(`${label}: expected a non-empty array of strings`);
  }
  // Sorted so the emitted file is stable regardless of source ordering.
  return [...(value as string[])].sort();
}

function union(names: readonly string[]): string {
  return names.map((n) => `  | ${JSON.stringify(n)}`).join("\n");
}

const keycodes = readJson(KEYCODES) as Record<string, unknown>;
const schema = readJson(SCHEMA);

const modifiers = strings(
  at(schema, ["$defs", "fromModifiers", "properties", "mandatory", "anyOf", 0, "items", "enum"], "schema"),
  "modifier enum",
);
const anyTypes = strings(
  at(schema, ["$defs", "fromEventDefinition", "properties", "any", "enum"], "schema"),
  "from.any enum",
);

const sections = TABLES.map(([json, ts]) => {
  const names = strings(keycodes[json], json);
  return [
    `/** \`${json}\` — ${names.length} names, from the parser's own tables. */`,
    `export type ${ts} =`,
    `${union(names)};`,
  ].join("\n");
});

const body = `// GENERATED by scripts/gen-key-types.ts — do not edit.
// Source: schema/karabiner-keycodes.json, schema/karabiner-rule.schema.json
// Regenerate: npm run codegen

/** Event-key families accepted by \`from.any\` and \`to.any\`. */
export type AnyEventType =
${union(anyTypes)};

/**
 * The full modifier enum, \`"any"\` included.
 *
 * \`"any"\` is meaningful only in \`from.modifiers\`. The parser accepts it in
 * \`to.modifiers\` but maps it to no modifier flag at all, so it is a silent
 * no-op there (gotcha 3.8). Consumers should reach for \`FromModifier\` /
 * \`ToModifier\` from ./karabiner rather than this type.
 */
export type KarabinerModifierOrAny =
${union(modifiers)};

${sections.join("\n\n")}
`;

let current: string | null = null;
try {
  current = readFileSync(OUT, "utf8");
} catch {
  current = null;
}

const label = relative(REPO, OUT);

if (process.argv.includes("--check")) {
  if (current !== body) {
    console.error(`✗ ${label} is stale — run: npm run codegen`);
    process.exitCode = 1;
  } else {
    console.log(`✓ ${label} up to date`);
  }
} else if (current === body) {
  console.log(`= ${label} unchanged`);
} else {
  writeFileSync(OUT, body);
  console.log(`✓ wrote ${label}`);
}
